### PR TITLE
Styling for challenge cards

### PR DESCRIPTION
**Pull request by solidtop**
Ser inte jättesnyggt ut när korten blir större men det är en fungerande responsiv layout :)..

2022-11-30 15_18_08- ESC  Our challenges — Mozilla Firefox

2022-11-30 15_17_40- ESC  Our challenges — Mozilla Firefox

### CODE REVIEW

**Review by matodorovic — APPROVED** [review]
It looks very good. Just a thought maybe to change color of icons to $c-darkblue: #011827; like background for header and footer.

**Comment by solidtop** [comment]
> It looks very good. Just a thought maybe to change color of icons to $c-darkblue: #011827; like background for header and footer.

**Review by davidlidebrandt — COMMENTED** [review]
Det ser bra ut!

**Review by davidlidebrandt — APPROVED** [review]

**Comment by matodorovic** [comment]
It looks like it is ready to be merged :)

**Pull request merged**
